// packages/vue/src/components/UnLazyImage.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watchEffect } from 'vue'
import { lazyLoad } from 'unlazy'

const props = defineProps<{
  /**
   * A flag to indicate whether the sizes attribute should be automatically calculated.
   * @default false
   */
  autoSizes?: boolean
  /** A BlurHash string representing the blurry placeholder image. */
  blurhash?: string
  /** A ThumbHash string representing the blurry placeholder image. */
  thumbhash?: string
  /** The size of the longer edge (width or height) of the BlurHash image to be decoded, depending on the aspect ratio. This option only applies when the `blurhash` prop is used. */
  placeholderSize?: number
}>()

const target = ref<HTMLImageElement | undefined>()
let cleanup: () => void | undefined

onMounted(() => {
  watchEffect(() => {
    cleanup?.()

    if (!target.value)
      return

    cleanup = lazyLoad(target.value, {
      hash: props.thumbhash || props.blurhash,
      hashType: props.thumbhash ? 'thumbhash' : 'blurhash',
      placeholderSize: props.placeholderSize,
    })
  })
})

onBeforeUnmount(() => {
  cleanup?.()
})
</script>

<template>
  <img
    ref="target"
    :data-sizes="autoSizes ? 'auto' : undefined"
    loading="lazy"
  >
</template>

// packages/svelte/src/components/UnLazyImage.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { lazyLoad } from 'unlazy'

  /** A flag to indicate whether the sizes attribute should be automatically calculated. */
  export let autoSizes:boolean = false;
  /** A BlurHash string representing the blurry placeholder image. */
  export let blurhash:string|undefined = undefined;
  /** A ThumbHash string representing the blurry placeholder image. */
  export let thumbhash:string|undefined = undefined;
  /** The size of the longer edge (width or height) of the BlurHash image to be decoded, depending on the aspect ratio. This option only applies when the `blurhash` prop is used. */
  export let placeholderSize:number = 600;

  let target:HTMLImageElement

  function initLazyLoad() {
    if(!!target) {
      lazyLoad(target, {
        hash: thumbhash ? thumbhash : blurhash,
        hashType: thumbhash ? 'thumbhash' : 'blurhash',
        placeholderSize: placeholderSize,
      })
    }
  }

  $: [blurhash, thumbhash, placeholderSize], initLazyLoad();

  onMount(initLazyLoad);
</script>

<img
  bind:this={target}
  data-sizes="{autoSizes ? 'auto' : null}"
  loading="lazy"
  {...$$restProps}
/>
