// packages/svelte/playground/App.svelte
<script lang="ts">
  import UnLazyImage from '../src/components/UnLazyImage.svelte'
</script>

<UnLazyImage
  blurhash="LKO2:N%2Tw=w]~RBVZRi};RPxuwH"
  auto-sizes={true}
  data-srcset="image-320w.jpg 320w, image-640w.jpg 640w"
  width="640"
  height="640"
/>
<UnLazyImage
  thumbhash="1QcSHQRnh493V4dIh4eXh1h4kJUI"
  auto-sizes={true}
  data-srcset="image-320w.jpg 320w, image-640w.jpg 640w"
  width="480"
  height="640"
/>

// packages/react/playground/App.tsx
import { UnLazyImage } from '../src'

function App() {
  return (
    <>
      <UnLazyImage
        blurhash="LKO2:N%2Tw=w]~RBVZRi};RPxuwH"
        autoSizes={true}
        data-srcset="image-320w.jpg 320w, image-640w.jpg 640w"
        width="640"
        height="640"
      />
      <UnLazyImage
        thumbhash="1QcSHQRnh493V4dIh4eXh1h4kJUI"
        autoSizes={true}
        data-srcset="image-320w.jpg 320w, image-640w.jpg 640w"
        width="480"
        height="640"
    />
    </>
  )
}

export default App
